### ISSUE TITLE
创建用户，登录用户提示已存在，加群，居然给我拒了，呵呵，有意思

### ISSUE THREAD

**Issue by songqii** [lostvip-com/ruoyi-go#5]
配置文件没有redis port设置，需要手动加上
初始化sql，自动导入了4张表，其它需要手动导入，不然找不到sys_config
系统里什么都建不了，各种报已存在

**Comment by songqii** [comment]
func (svc *DeptService) CheckDeptNameUniqueAll(deptName string, parentId int64) string {
	var dao dao.SysDeptDao
	dept, err := dao.CheckDeptNameUniqueAll(deptName, parentId)
	if err != nil {
		return "1"
	}
	if dept != nil && dept.DeptId > 0 {
		return "1"
	} else {
		return "0"
	}
}
------------------------------------------------
这代码写的，有点不地道了，error不往上面报，你好歹有个日志提示下开发者

**Comment by lostvip-com** [comment]
必须star 呵呵

**Comment by lostvip-com** [comment]
感谢指正

**Comment by lostvip-com** [comment]
> 配置文件没有redis port设置，需要手动加上 初始化sql，自动导入了4张表，其它需要手动导入，不然找不到sys_config 系统里什么都建不了，各种报已存在
配置文件模仿的springboot 框架，有两个配置文件 redis配置在 application.yml
